# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Firebase CI

on:

  pull_request:
    branches: [ master ]

jobs:
  build_and_preview:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
        npm ci
         npm run build
     - uses: FirebaseExtended/action-hosting-deploy@v0
       with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 30d
          projectId: knowaste-3c92
     - uses: actions/checkout@v2
